namespace BaseLib.Config;

/// <summary>
/// Creates a new section in the ModConfig UI, where the next property will be the first entry after the section header.
/// </summary>
/// <param name="name">The LocString name. Will be transformed just like property names, so for "FirstSection", you need to
/// specify a value for YOURMOD-FIRST_SECTION.title in the localization file(s).</param>
[AttributeUsage(AttributeTargets.Property)]
public class ConfigSectionAttribute(string name) : Attribute
{
    public string Name { get; } = name;
}

/// <summary>
/// Specifies a range and step for a slider. Negative numbers are supported, as are noninteger numbers.<br/>
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class SliderRangeAttribute : Attribute
{
    public double Min { get; }
    public double Max { get; }
    public double Step { get; }

    public SliderRangeAttribute(double min, double max, double step = 1.0)
    {
        if (min > max)
        {
            throw new ArgumentException($"SliderRange: Min ({min}) cannot be greater than Max ({max}).");
        }

        if (step <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(step), "SliderRange: Step must be greater than 0.");
        }

        Min = min;
        Max = max;
        Step = step;
    }
}

/// <summary>
/// The string format to us for the slider's label. Uses standard C# format, see <see cref="String.Format(string, object?)"/>.
/// </summary>
/// <param name="format"></param>
[AttributeUsage(AttributeTargets.Property)]
public class SliderLabelFormatAttribute(string format) : Attribute
{
    public string Format { get; } = format;
}

/// <summary>
/// <para>Show a tooltip for this setting on hover. Requires a settings_ui.json localization file.
/// The names used are typically:</para>
/// YOURMOD-PROPERTY_NAME.hover.title (optional, if missing, no title will be shown)<br/>
/// YOURMOD-PROPERTY_NAME.hover.desc (required)
/// </summary>
/// <param name="enabled">Enable hover tip for this property. Can be set to false in order to add exceptions for <see cref="HoverTipsByDefaultAttribute"/></param>
[AttributeUsage(AttributeTargets.Property)]
public class ConfigHoverTipAttribute(bool enabled = true) : Attribute
{
    public bool Enabled { get; } = enabled;
}

/// <summary>
/// Attempt to add hover tips to ALL config properties in this class. Use <see cref="ConfigHoverTipAttribute"/> with
/// enabled=false to add exceptions. Still requires .hover.desc entries in your localization file, see <see cref="ConfigHoverTipAttribute"/>.
/// </summary>
[AttributeUsage(AttributeTargets.Class)]
public class HoverTipsByDefaultAttribute : Attribute;

/// <summary>
/// Completely ignores this property. It will not be loaded or saved, and will not be shown for auto-generated UI.<br/>
/// Intended for properties that aren't configuration options at all.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class ConfigIgnoreAttribute : Attribute;

/// <summary>
/// Saves and loads this property to the config file normally, but generate no UI for it in SimpleModConfig.<br/>
/// Intended for when you want to create the UI manually, or easily persist things that aren't user-configurable (e.g.
/// total gold gained / number of runs played with the mod active).
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class ConfigHideInUI : Attribute;

/// <summary>
/// Defines a set of allowed characters for a LineEdit.
/// </summary>
public enum TextInputPreset
{
    /// <summary>The default. No validation at all.</summary>
    Anything,
    /// <summary>English letters and numbers (a-z, A-Z, 0-9).</summary>
    Alphanumeric,
    /// <summary>English letters, numbers (a-z, A-Z, 0-9) and spaces.</summary>
    AlphanumericWithSpaces,
    /// <summary>Allows international letters, numbers, spaces, underscores, and hyphens.</summary>
    SafeDisplayName,
}

/// <summary>
/// <para>Defines the allowed characters and max length for the LineEdit generated by a string property.<br/>
/// You can specify a <see cref="TextInputPreset"/> or a custom Regex string for the allowed characters. By default,
/// any string is allowed, at any length.</para>
/// If a placeholder LocString exists (YOURMOD-PROPERTY_NAME.placeholder), it will be used; if you don't want a
/// placeholder, simply skip creating such a string.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class ConfigTextInputAttribute : Attribute
{
    public string AllowedCharactersRegex { get; }
    public int MaxLength { get; set; } = 0;

    public ConfigTextInputAttribute(TextInputPreset preset)
    {
        AllowedCharactersRegex = preset switch
        {
            TextInputPreset.Alphanumeric => "[a-zA-Z0-9]+",
            TextInputPreset.AlphanumericWithSpaces => "[a-zA-Z0-9 ]+",
            TextInputPreset.SafeDisplayName => @"[\p{L}\d_\- ]+",
            TextInputPreset.Anything or _ => ".*",
        };
    }

    public ConfigTextInputAttribute(string customRegex)
    {
        AllowedCharactersRegex = customRegex;
    }
}

/// <summary>
/// <para>Creates a clickable button from a method. Source code order is respected, so if the method is defined in between
/// two properties, the button will be in between their respective controls.</para>
/// <para>The method supports having any of these different arguments injected with any name, in any order (only the type is used):</para>
/// <br/>
///   <b>ModConfig</b>: Injects the instance of your ModConfig (may be useful if the method is static).<br />
///   <b>NConfigButton</b>: Injects the instance of the button that was clicked.<br />
///   <b>NConfigOptionRow</b>: Injects the instance of the row the button belongs to (the node that handles its layout, hover tip, etc.).<br />
/// </summary>
/// <param name="buttonLabelKey">LocString key for the text on the button.</param>
[AttributeUsage(AttributeTargets.Method)]
public class ConfigButtonAttribute(string buttonLabelKey) : Attribute
{
    public string ButtonLabelKey { get; } = buttonLabelKey;
}